# Die Pandas Bibliothek

## Überblick

* de facto Standard für Datenanalyse-Programm in Python
* Open Source
    * Lizenzfrei in der Nutzung
    * [Homepage](https://pandas.pydata.org/)
    * [Dokumentation](https://pandas.pydata.org/docs/reference/index.html)
* Funktionsumfang
    * Unterstützung aller gängiger Datenformate, Lesend und Schreibend
    * Spezielle Collection, der DataFrame
    * Unterstützung von Grafiken = Diagrammen
    * Integration der deskriptiven Statistik, also Mittelwerte, Abweichungen, etc.
    * Integration weiterer Bibliotheken, z.B. matplotlib, scikit für Machine Learning

# Installation

In [ ]:
pip install pandas

## Einführung in die Programmierung mit Pandas

### Import

In [ ]:
import pandas as pd

### Laden eines CSV-Datensatzes

In [ ]:
pd.read_csv('people_data.csv')

### Laden des Datensatzen und Zuweisung an eine Variable

* Typ der Variablen ist ein Pandas-DataFrame

In [ ]:
df = pd.read_csv('people_data.csv')
df

### Exploration des Datensatzes

* head() und tail()
    * Standardgröße ist 5
    * head(3)

In [ ]:
df.head(3)

* Info und Describe

In [ ]:
df.info()

In [ ]:
df.describe()

* Unsaubere Eingangsdaten

In [ ]:
dirty_df = pd.read_csv('people_data_dirty.csv')
dirty_df.info()

In [ ]:
dirty_df = pd.read_csv('people_data_very_dirty.csv') #height manipuliert --> "1.92xxx" - Dtype wird zu object
dirty_df.info()

### DataFrame als Datencontainer / Collection

* Elementare Berechnungen / Zugriffe

In [ ]:
height_series = df['height'] + 1
print(height_series)

In [ ]:
df['weight']/(df['height']**2) #BMI Berechnung

In [ ]:
bmi = df['weight']/(df['height']**2)
bmi

In [ ]:
bmi.info()

In [ ]:
bmi.describe()

* Zuweisung einer Series an einen DataFrame

In [ ]:
df['bmi'] = df['weight']/(df['height']**2) #BMI Spalte hinzugefügt
df.info()

* Entfernen einer Series aus einem DataFrame

In [ ]:
df.drop('GENDER', axis=1)
df.drop(columns=['GENDER'])

* Detail: inplace_Operation

In [ ]:
df.drop(columns=['GENDER'], inplace=True)
df

## Indexzugriff

In [96]:
df.index[0]

0

In [104]:
slice_df = df.loc[0:2, ['weight', 'height']] #type: DataFrame
slice_df.describe()

          weight    height
count   3.000000  3.000000
mean   91.866667  1.703333
std     6.401042  0.040415
min    85.400000  1.680000
25%    88.700000  1.680000
50%    92.000000  1.680000
75%    95.100000  1.715000
max    98.200000  1.750000

In [107]:
slice_df = df.iloc[0:2, 3] 
slice_df.describe()

count    2.00
mean     1.68
std      0.00
min      1.68
25%      1.68
50%      1.68
75%      1.68
max      1.68
Name: height, dtype: float64

### Vergleichsoperatoren

In [112]:
df['height'] > 1.90

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: height, Length: 100, dtype: bool

In [111]:
selection_vector = df['height'] > 1.90
df[selection_vector]

    id firstname   lastname  height  weight        bmi
9   10     Brian      Brown    1.92    61.4  16.655816
22  23      Mary  Dickerson    1.91    95.4  26.150599
28  29  Margaret      Evans    1.96    86.5  22.516660
38  39  Kimberly      Jones    1.97    73.4  18.913139
40  41    Robert      Green    1.99    72.4  18.282367
46  47      Mary      Myers    1.99    73.4  18.534885
50  51    Cheryl      Young    1.95    90.4  23.773833
65  66     Jenny    Frazier    1.98    93.5  23.849607
73  74     James    Delgado    1.98    97.0  24.742373
76  77      Ryan       Lane    1.97    51.6  13.295885
79  80    Autumn     Watson    1.94    89.7  23.833564
80  81      Luis     Miller    1.92    83.1  22.542318
84  85   Jessica      Allen    1.98    97.3  24.818896
90  91    George      Jones    1.91    51.8  14.199172

In [117]:
tall_people_df = df[df['height'] > 1.90]
tall_people_df
tall_people_df.describe()

              id     height     weight        bmi
count  14.000000  14.000000  14.000000  14.000000
mean   56.714286   1.955000  79.778571  20.864937
std    25.838042   0.029807  16.061812   4.166524
min    10.000000   1.910000  51.600000  13.295885
25%    39.500000   1.925000  72.650000  18.345496
50%    58.500000   1.965000  84.800000  22.529489
75%    79.250000   1.980000  92.725000  23.845596
max    91.000000   1.990000  97.300000  26.150599

### Lesen aus anderen Formaten und Quellen

* JSON

In [120]:
df = pd.read_json('http://javacream.eu:8080/people')
df

   id    lastname  firstname gender  height
0   1    Sawitzki     Rainer      m     183
1   2       Meier       Hans      m     163
2   3     Metzger      Georg      m     190
3   4     Metzger     Frieda      f     167
4   5    Hoffmann      Hanna      f     155
5   6  Pausenkurt     Pascal      m     177
6   7       Fisch      Wanda      f     164
7   8     Ziegler     Thomas      m     193
8   9        Tost  Franziska      f     177
9  10      Berger       Hans      m     183

In [121]:
df.describe()

             id      height
count  10.00000   10.000000
mean    5.50000  175.200000
std     3.02765   12.532624
min     1.00000  155.000000
25%     3.25000  164.750000
50%     5.50000  177.000000
75%     7.75000  183.000000
max    10.00000  193.000000